module_name = "ImGuiTestEngine"
uuid = "d6eb4cb6-1e07-14c4-5835-ae91bedf8555"
include_dirs = [".", "./imgui_test_engine/imgui_test_engine", "../cimgui/imgui"]
input = ["imgui_te_engine.h", "imgui_te_internal.h", "imgui_te_context.h",
         "imgui_te_perftool.h", "imgui_te_ui.h", "imgui_te_utils.h", "imgui_te_exporters.h",
         "overrides.h"]
cxx-std = "c++17"
out_cxx_dir = "src"

veto_list = "veto_list.txt"
extra_headers = ["imgui.h", "imgui_internal.h", "thirdparty/Str/Str.h"]
clang_opts = ["-DIMGUI_TEST_ENGINE_ENABLE_STD_FUNCTION=1", "-DIMGUI_DISABLE_OBSOLETE_FUNCTIONS=1",
              "-I{CXXWRAP_INCLUDE_DIR}",
              "-I{JULIA_INCLUDE_DIR}"]
lib_basename = "$(@__DIR__)/../../../build/libcimgui"
export = "none"
vetoed_copy_ctor_classes = ["ImGuiContext"]
